[package]
name = "vstea"
version = "0.1.0"
authors = ["Mark Wissink <mwissink.b@gmail.com>"]

[dependencies]
midir = "0.5.0"
piston_window = "0.70.0"

[dependencies.fluidsynth]
git = "https://github.com/elidupree/rust-fluidsynth"
